# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders: 
     Symfony\Component\Security\Core\User\User: plaintext
     SeeItAll\UserBundle\Entity\User: sha512
     

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:       [ROLE_EDITOR]
        ROLE_EDITOR:      [ROLE_VIEWER]
        


    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        
        db_provider :   
                id: fos_user.user_provider.username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        mustafa:
            pattern:   ^/
            anonymous: true
            provider: db_provider
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login

            remember_me:
                secret:     %secret% # %secret% est un paramètre de parameter

    access_control:
        - { path: ^/levels, role: ROLE_VIEWER, requires_channel: https }
        - { path: ^/remove, role: ROLE_EDITOR, requires_channel: https }
        - { path: ^/docs,   role: ROLE_VIEWER,  requires_channel: https }
        
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
