<?php

namespace SeeItAll\assetXploreBundle\Repository;

/**
 * App_dbRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class App_dbRepository extends \Doctrine\ORM\EntityRepository
{
}
