<?php

namespace SeeItAll\assetXploreBundle\Repository;

/**
 * Level0Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class Level0Repository  extends \Doctrine\ORM\EntityRepository
{
}
