<?php

namespace SeeItAll\assetXploreBundle\Repository;

/**
 * roomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Level5Repository extends \Doctrine\ORM\EntityRepository
{
}
